package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class DataSourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceAllPropertiesEquals(DataSource expected, DataSource actual) {
        assertDataSourceAutoGeneratedPropertiesEquals(expected, actual);
        assertDataSourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceAllUpdatablePropertiesEquals(DataSource expected, DataSource actual) {
        assertDataSourceUpdatableFieldsEquals(expected, actual);
        assertDataSourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceAutoGeneratedPropertiesEquals(DataSource expected, DataSource actual) {
        assertThat(actual)
            .as("Verify DataSource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceUpdatableFieldsEquals(DataSource expected, DataSource actual) {
        assertThat(actual)
            .as("Verify DataSource relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getHostname()).as("check hostname").isEqualTo(expected.getHostname()))
            .satisfies(a -> assertThat(a.getPort()).as("check port").isEqualTo(expected.getPort()))
            .satisfies(a -> assertThat(a.getSchemaName()).as("check schemaName").isEqualTo(expected.getSchemaName()))
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getPassword()).as("check password").isEqualTo(expected.getPassword()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceUpdatableRelationshipsEquals(DataSource expected, DataSource actual) {
        // empty method
    }
}
