package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class DataSyncTableConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncTableConfigAllPropertiesEquals(DataSyncTableConfig expected, DataSyncTableConfig actual) {
        assertDataSyncTableConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertDataSyncTableConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncTableConfigAllUpdatablePropertiesEquals(DataSyncTableConfig expected, DataSyncTableConfig actual) {
        assertDataSyncTableConfigUpdatableFieldsEquals(expected, actual);
        assertDataSyncTableConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncTableConfigAutoGeneratedPropertiesEquals(DataSyncTableConfig expected, DataSyncTableConfig actual) {
        assertThat(actual)
            .as("Verify DataSyncTableConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncTableConfigUpdatableFieldsEquals(DataSyncTableConfig expected, DataSyncTableConfig actual) {
        assertThat(actual)
            .as("Verify DataSyncTableConfig relevant properties")
            .satisfies(a -> assertThat(a.getSyncTask()).as("check syncTask").isEqualTo(expected.getSyncTask()))
            .satisfies(a -> assertThat(a.getSrcDatasource()).as("check srcDatasource").isEqualTo(expected.getSrcDatasource()))
            .satisfies(a -> assertThat(a.getSrcSchemaName()).as("check srcSchemaName").isEqualTo(expected.getSrcSchemaName()))
            .satisfies(a -> assertThat(a.getSrcTableName()).as("check srcTableName").isEqualTo(expected.getSrcTableName()))
            .satisfies(a -> assertThat(a.getSrcColPks()).as("check srcColPks").isEqualTo(expected.getSrcColPks()))
            .satisfies(a -> assertThat(a.getDesDatasource()).as("check desDatasource").isEqualTo(expected.getDesDatasource()))
            .satisfies(a -> assertThat(a.getDesSchemaName()).as("check desSchemaName").isEqualTo(expected.getDesSchemaName()))
            .satisfies(a -> assertThat(a.getDesTableName()).as("check desTableName").isEqualTo(expected.getDesTableName()))
            .satisfies(a -> assertThat(a.getDesColPks()).as("check desColPks").isEqualTo(expected.getDesColPks()))
            .satisfies(a -> assertThat(a.getJobDesc()).as("check jobDesc").isEqualTo(expected.getJobDesc()))
            .satisfies(a -> assertThat(a.getColumeConfig()).as("check columeConfig").isEqualTo(expected.getColumeConfig()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()))
            .satisfies(a -> assertThat(a.getDr()).as("check dr").isEqualTo(expected.getDr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncTableConfigUpdatableRelationshipsEquals(DataSyncTableConfig expected, DataSyncTableConfig actual) {
        // empty method
    }
}
