package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class DataSyncAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncAllPropertiesEquals(DataSync expected, DataSync actual) {
        assertDataSyncAutoGeneratedPropertiesEquals(expected, actual);
        assertDataSyncAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncAllUpdatablePropertiesEquals(DataSync expected, DataSync actual) {
        assertDataSyncUpdatableFieldsEquals(expected, actual);
        assertDataSyncUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncAutoGeneratedPropertiesEquals(DataSync expected, DataSync actual) {
        assertThat(actual)
            .as("Verify DataSync auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncUpdatableFieldsEquals(DataSync expected, DataSync actual) {
        assertThat(actual)
            .as("Verify DataSync relevant properties")
            .satisfies(a -> assertThat(a.getJobName()).as("check jobName").isEqualTo(expected.getJobName()))
            .satisfies(a -> assertThat(a.getJobCode()).as("check jobCode").isEqualTo(expected.getJobCode()))
            .satisfies(a -> assertThat(a.getJobDesc()).as("check jobDesc").isEqualTo(expected.getJobDesc()))
            .satisfies(a -> assertThat(a.getDir()).as("check dir").isEqualTo(expected.getDir()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getCron()).as("check cron").isEqualTo(expected.getCron()))
            .satisfies(a -> assertThat(a.getJobContext()).as("check jobContext").isEqualTo(expected.getJobContext()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getLastStatus()).as("check lastStatus").isEqualTo(expected.getLastStatus()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()))
            .satisfies(a -> assertThat(a.getDr()).as("check dr").isEqualTo(expected.getDr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSyncUpdatableRelationshipsEquals(DataSync expected, DataSync actual) {
        // empty method
    }
}
