package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class DpTableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDpTableAllPropertiesEquals(DpTable expected, DpTable actual) {
        assertDpTableAutoGeneratedPropertiesEquals(expected, actual);
        assertDpTableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDpTableAllUpdatablePropertiesEquals(DpTable expected, DpTable actual) {
        assertDpTableUpdatableFieldsEquals(expected, actual);
        assertDpTableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDpTableAutoGeneratedPropertiesEquals(DpTable expected, DpTable actual) {
        assertThat(actual)
            .as("Verify DpTable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDpTableUpdatableFieldsEquals(DpTable expected, DpTable actual) {
        assertThat(actual)
            .as("Verify DpTable relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSchemaName()).as("check schemaName").isEqualTo(expected.getSchemaName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSourceDBType()).as("check sourceDBType").isEqualTo(expected.getSourceDBType()))
            .satisfies(a -> assertThat(a.getSourceId()).as("check sourceId").isEqualTo(expected.getSourceId()))
            .satisfies(a -> assertThat(a.getSourceSchema()).as("check sourceSchema").isEqualTo(expected.getSourceSchema()))
            .satisfies(a -> assertThat(a.getSourceTable()).as("check sourceTable").isEqualTo(expected.getSourceTable()))
            .satisfies(a -> assertThat(a.getSqlContent()).as("check sqlContent").isEqualTo(expected.getSqlContent()))
            .satisfies(a -> assertThat(a.getFileType()).as("check fileType").isEqualTo(expected.getFileType()))
            .satisfies(a -> assertThat(a.getFilePath()).as("check filePath").isEqualTo(expected.getFilePath()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDpTableUpdatableRelationshipsEquals(DpTable expected, DpTable actual) {
        // empty method
    }
}
