package com.data.datafusion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ETLEdgeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLEdgeAllPropertiesEquals(ETLEdge expected, ETLEdge actual) {
        assertETLEdgeAutoGeneratedPropertiesEquals(expected, actual);
        assertETLEdgeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLEdgeAllUpdatablePropertiesEquals(ETLEdge expected, ETLEdge actual) {
        assertETLEdgeUpdatableFieldsEquals(expected, actual);
        assertETLEdgeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLEdgeAutoGeneratedPropertiesEquals(ETLEdge expected, ETLEdge actual) {
        assertThat(actual)
            .as("Verify ETLEdge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLEdgeUpdatableFieldsEquals(ETLEdge expected, ETLEdge actual) {
        assertThat(actual)
            .as("Verify ETLEdge relevant properties")
            .satisfies(a -> assertThat(a.getTaskId()).as("check taskId").isEqualTo(expected.getTaskId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getConfig()).as("check config").isEqualTo(expected.getConfig()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()))
            .satisfies(a -> assertThat(a.getDr()).as("check dr").isEqualTo(expected.getDr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLEdgeUpdatableRelationshipsEquals(ETLEdge expected, ETLEdge actual) {
        // empty method
    }
}
