package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ETLNodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLNodeAllPropertiesEquals(ETLNode expected, ETLNode actual) {
        assertETLNodeAutoGeneratedPropertiesEquals(expected, actual);
        assertETLNodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLNodeAllUpdatablePropertiesEquals(ETLNode expected, ETLNode actual) {
        assertETLNodeUpdatableFieldsEquals(expected, actual);
        assertETLNodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLNodeAutoGeneratedPropertiesEquals(ETLNode expected, ETLNode actual) {
        assertThat(actual)
            .as("Verify ETLNode auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLNodeUpdatableFieldsEquals(ETLNode expected, ETLNode actual) {
        assertThat(actual)
            .as("Verify ETLNode relevant properties")
            .satisfies(a -> assertThat(a.getTaskId()).as("check taskId").isEqualTo(expected.getTaskId()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDesc()).as("check desc").isEqualTo(expected.getDesc()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getConfig()).as("check config").isEqualTo(expected.getConfig()))
            .satisfies(a -> assertThat(a.getxAxis()).as("check xAxis").isEqualTo(expected.getxAxis()))
            .satisfies(a -> assertThat(a.getyAxis()).as("check yAxis").isEqualTo(expected.getyAxis()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()))
            .satisfies(a -> assertThat(a.getDr()).as("check dr").isEqualTo(expected.getDr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLNodeUpdatableRelationshipsEquals(ETLNode expected, ETLNode actual) {
        // empty method
    }
}
