package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ETLTaskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLTaskAllPropertiesEquals(ETLTask expected, ETLTask actual) {
        assertETLTaskAutoGeneratedPropertiesEquals(expected, actual);
        assertETLTaskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLTaskAllUpdatablePropertiesEquals(ETLTask expected, ETLTask actual) {
        assertETLTaskUpdatableFieldsEquals(expected, actual);
        assertETLTaskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLTaskAutoGeneratedPropertiesEquals(ETLTask expected, ETLTask actual) {
        assertThat(actual)
            .as("Verify ETLTask auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLTaskUpdatableFieldsEquals(ETLTask expected, ETLTask actual) {
        assertThat(actual)
            .as("Verify ETLTask relevant properties")
            .satisfies(a -> assertThat(a.getTaskName()).as("check taskName").isEqualTo(expected.getTaskName()))
            .satisfies(a -> assertThat(a.getTaskCode()).as("check taskCode").isEqualTo(expected.getTaskCode()))
            .satisfies(a -> assertThat(a.getJobId()).as("check jobId").isEqualTo(expected.getJobId()))
            .satisfies(a -> assertThat(a.getTaskDesc()).as("check taskDesc").isEqualTo(expected.getTaskDesc()))
            .satisfies(a -> assertThat(a.getDir()).as("check dir").isEqualTo(expected.getDir()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getCron()).as("check cron").isEqualTo(expected.getCron()))
            .satisfies(a -> assertThat(a.getJobContext()).as("check jobContext").isEqualTo(expected.getJobContext()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getLastStatus()).as("check lastStatus").isEqualTo(expected.getLastStatus()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getCreater()).as("check creater").isEqualTo(expected.getCreater()))
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()))
            .satisfies(a -> assertThat(a.getDr()).as("check dr").isEqualTo(expected.getDr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertETLTaskUpdatableRelationshipsEquals(ETLTask expected, ETLTask actual) {
        // empty method
    }
}
