package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class JobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobAllPropertiesEquals(Job expected, Job actual) {
        assertJobAutoGeneratedPropertiesEquals(expected, actual);
        assertJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobAllUpdatablePropertiesEquals(Job expected, Job actual) {
        assertJobUpdatableFieldsEquals(expected, actual);
        assertJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobAutoGeneratedPropertiesEquals(Job expected, Job actual) {
        assertThat(actual)
            .as("Verify Job auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobUpdatableFieldsEquals(Job expected, Job actual) {
        assertThat(actual)
            .as("Verify Job relevant properties")
            .satisfies(a -> assertThat(a.getJobName()).as("check jobName").isEqualTo(expected.getJobName()))
            .satisfies(a -> assertThat(a.getJobGroup()).as("check jobGroup").isEqualTo(expected.getJobGroup()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getCron()).as("check cron").isEqualTo(expected.getCron()))
            .satisfies(a -> assertThat(a.getJobContext()).as("check jobContext").isEqualTo(expected.getJobContext()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdateTime())
            )
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobUpdatableRelationshipsEquals(Job expected, Job actual) {
        // empty method
    }
}
