package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class JobDependAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDependAllPropertiesEquals(JobDepend expected, JobDepend actual) {
        assertJobDependAutoGeneratedPropertiesEquals(expected, actual);
        assertJobDependAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDependAllUpdatablePropertiesEquals(JobDepend expected, JobDepend actual) {
        assertJobDependUpdatableFieldsEquals(expected, actual);
        assertJobDependUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDependAutoGeneratedPropertiesEquals(JobDepend expected, JobDepend actual) {
        assertThat(actual)
            .as("Verify JobDepend auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDependUpdatableFieldsEquals(JobDepend expected, JobDepend actual) {
        assertThat(actual)
            .as("Verify JobDepend relevant properties")
            .satisfies(a -> assertThat(a.getParentJobCode()).as("check parentJobCode").isEqualTo(expected.getParentJobCode()))
            .satisfies(a -> assertThat(a.getChildJobCode()).as("check childJobCode").isEqualTo(expected.getChildJobCode()))
            .satisfies(a -> assertThat(a.getJobCode()).as("check jobCode").isEqualTo(expected.getJobCode()))
            .satisfies(a -> assertThat(a.getLastInterval()).as("check lastInterval").isEqualTo(expected.getLastInterval()))
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDependUpdatableRelationshipsEquals(JobDepend expected, JobDepend actual) {
        // empty method
    }
}
