package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class JobInstanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobInstanceAllPropertiesEquals(JobInstance expected, JobInstance actual) {
        assertJobInstanceAutoGeneratedPropertiesEquals(expected, actual);
        assertJobInstanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobInstanceAllUpdatablePropertiesEquals(JobInstance expected, JobInstance actual) {
        assertJobInstanceUpdatableFieldsEquals(expected, actual);
        assertJobInstanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobInstanceAutoGeneratedPropertiesEquals(JobInstance expected, JobInstance actual) {
        assertThat(actual)
            .as("Verify JobInstance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobInstanceUpdatableFieldsEquals(JobInstance expected, JobInstance actual) {
        assertThat(actual)
            .as("Verify JobInstance relevant properties")
            .satisfies(a -> assertThat(a.getInstanceCode()).as("check instanceCode").isEqualTo(expected.getInstanceCode()))
            .satisfies(a -> assertThat(a.getJobName()).as("check jobName").isEqualTo(expected.getJobName()))
            .satisfies(a -> assertThat(a.getJobCode()).as("check jobCode").isEqualTo(expected.getJobCode()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getJobContext()).as("check jobContext").isEqualTo(expected.getJobContext()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getJobMessage()).as("check jobMessage").isEqualTo(expected.getJobMessage()))
            .satisfies(a -> assertThat(a.getExecNode()).as("check execNode").isEqualTo(expected.getExecNode()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobInstanceUpdatableRelationshipsEquals(JobInstance expected, JobInstance actual) {
        // empty method
    }
}
