package com.data.datafusion.domain;

import static com.data.datafusion.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ServiceConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConfigAllPropertiesEquals(ServiceConfig expected, ServiceConfig actual) {
        assertServiceConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConfigAllUpdatablePropertiesEquals(ServiceConfig expected, ServiceConfig actual) {
        assertServiceConfigUpdatableFieldsEquals(expected, actual);
        assertServiceConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConfigAutoGeneratedPropertiesEquals(ServiceConfig expected, ServiceConfig actual) {
        assertThat(actual)
            .as("Verify ServiceConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConfigUpdatableFieldsEquals(ServiceConfig expected, ServiceConfig actual) {
        assertThat(actual)
            .as("Verify ServiceConfig relevant properties")
            .satisfies(a -> assertThat(a.getDfGroup()).as("check dfGroup").isEqualTo(expected.getDfGroup()))
            .satisfies(a -> assertThat(a.getDfKey()).as("check dfKey").isEqualTo(expected.getDfKey()))
            .satisfies(a -> assertThat(a.getDfValue()).as("check dfValue").isEqualTo(expected.getDfValue()))
            .satisfies(a ->
                assertThat(a.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreateTime())
            )
            .satisfies(a -> assertThat(a.getTenantId()).as("check tenantId").isEqualTo(expected.getTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConfigUpdatableRelationshipsEquals(ServiceConfig expected, ServiceConfig actual) {
        // empty method
    }
}
